### ISSUE TITLE
0.5.7 doesn't get commands from HA

### ISSUE THREAD

**Issue by adizag** [TomerFi/switcher_webapi#285]
# Bug Report

**Describe the bug**
0.5.7 doesn't get commands from HA. after downgrade to 0.5.6 - it is working again
tried turn on, turn on for X minutes, turn off without response.
When activating manually, the HA is updated though.

**Docker image version**
0.5.7, then 0.5.6

**Comment by TomerFi** [comment]
Thank you for opening an issue.

I think this issue requires some more information:
What are the commands you are trying to send,
better yet if you can attach the request (**removing personal info**),
the response and the error produced if any.

**Comment by adizag** [comment]
@TomerFi 
sorry, it was solved by upgrading the switcher firmware. forgot to close the ticket.
TNX!!!
