### ISSUE TITLE
Better documentation site

### ISSUE THREAD

**Issue by TomerFi** [TomerFi/switcher_webapi#439]
### What did you had in mind?

Replace `sphinx` with `mkdocs` which seems better for this project.

For refs, [this](https://switcher-webapi.tomfi.info/) is the docs site for this project build with `sphinx`,
and [this](https://archetypes.tomfi.info/) is a docs site built for another project of mine, build with `mkdocs`.

**Comment by dolby360** [comment]
I can take this one as well
