### ISSUE TITLE
Support new devices

### ISSUE THREAD

**Issue by TomerFi** [TomerFi/switcher_webapi#540]
### What did you have in mind?

[aioswitcher 3.0.0](https://github.com/TomerFi/aioswitcher/releases/tag/3.0.0) introduced support for _Runners_ and _Breeze_ devices, these modifications should be implemented here as well.

**Comment by dolby360** [comment]
ME!!!!!!

**Comment by TomerFi** [comment]
Thank you very much @dolby360 .
🚀

**Comment by dolby360** [comment]
No problem.
Please help me understand this API function 
```python 
async def control_breeze_device(
        self,
        command: SwitcherBreezeCommand,
    )
```
When I look at the class `SwitcherBreezeCommand` I see
```python
  def __init__(self, command):
      """Initialize the Breeze command."""
      self.command = command
      self.length = self._get_command_length()
```
Unfortunately `command` has no type :( 
What is the expected input for this function? 


BTW this is definitely not a "good first issue" :)

@TomerFi

**Comment by dolby360** [comment]
I'm done with the others:
```
set_position
get_breeze_state
get_shutter_state
stop
```

**Comment by TomerFi** [comment]
take a look here https://github.com/home-assistant/core/pull/78596, Shay implemented this for Home Assistant.

**Comment by TomerFi** [comment]
@dolby360 I updated aioswitcher's README with example usage snippets.

**Comment by dolby360** [comment]
@TomerFi Will you be able to help me with this function? I will upload the PR just add a commit.
I spent the whole weekend to understand it  :(

**Comment by TomerFi** [comment]
yes of course, push the PR and we'll work on this together.
I haven't used this function yet, but if we need, I'm sure Shay and Jafar will help us out.
:-)
