### ISSUE TITLE
switcher_webapi docker image arm64

### ISSUE THREAD

**Issue by gargamelonly** [TomerFi/switcher_webapi#702]
Could you please add a docker image for arm64 configuration for running it on PiOS 64bit variant?

**Comment by TomerFi** [comment]
The last time I tried, I think some of the transitive dependencies didn't work for _arm64_ out-of-the-box, but I don't remember putting much effort to it. Regardless, it was a long time ago. This might be doable, but I don't think I'll have the capacity to do it anytime soon. Contributions will be happily accepted.

**Comment by gargamelonly** [comment]
עשתי git clone לתיקייה. 
שיניתי את שורה 9 ב Makefile  ל PLATFORMS = linux/amd64,linux/arm/v7,linux/arm64/v8
אחר כך הרצתי docker build -t switcher_webapi .
האימג' נוצר בתיקייה /var/lib/docker
ואז בקומפוז קראתי לו ישר switcher_webapi  בלי הקידומת
לא נתקלתי בשגיאות.

**Comment by TomerFi** [comment]
Contributions will be happily accepted.

**Comment by YogevBokobza** [comment]
Addressed in https://github.com/TomerFi/switcher_webapi/pull/711

**Comment by TomerFi** [comment]
[1.3.0](https://github.com/TomerFi/switcher_webapi/releases/tag/1.3.0)
