### ISSUE TITLE
error after upgade

### ISSUE THREAD

**Issue by motti1111** [TomerFi/switcher_webapi#724]
### What happened?

getting this error:
KeyError: 'type'

### Module Version

2.0.0

### Device Type

Switcher V2

### Firmware Version

3.4.5

### Relevant log output

```shell
2024-10-18 12:02:19,597 - aiohttp.server - ERROR - caught exception while handing over to endpoint
Traceback (most recent call last):
  File "/usr/switcher_webapi/webapp.py", line 422, in error_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/switcher_webapi/webapp.py", line 120, in get_state
    device_type = DEVICES[request.query[KEY_TYPE]]
                          ~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'type'
```

**Comment by TomerFi** [comment]
Hi

Thank you for reporting.
This is not a bug. Since version 2.0.0, every request requires a type; see the release info:
https://github.com/TomerFi/switcher_webapi/releases/tag/2.0.0

![image](https://github.com/user-attachments/assets/8f50ee41-71ed-44a5-9fcf-38ee1c842bf2)

@dmatik @YogevBokobza - We should probably add some statement on the manner to the README.

**Comment by motti1111** [comment]
תודה רבה על המענה הסופר מהיר.

ראיתי את הדרישה ושיניתי בבקשות אצלי בHA, אבל הלוגים עדיין מלאים בשגיאה
יש דרך להבין מי שולח את בקשות?
יש מצב שזה מהפלגאין של סוויצר בHA?

תודה,
מוטי

בתאריך שבת, 19 באוק׳ 2024, 08:29, מאת Tomer Figenblat ‏<
***@***.***>:

**Comment by dmatik** [comment]
Do you have both Switcher integration and rest service using switch webapi in HA?
If so, why?
You should use one of them.

**Comment by motti1111** [comment]
האמת, כבר לא זוכר למה חחח
האינטגרציה מוסיפה לי את צריכה והסטטוס, שלא הצלחתי לקבל מה WebAPI ומצד שני
לא הצלחתי בזמנו להפעיל תזמון לדוד ללא השירות

בתאריך שבת, 19 באוק׳ 2024, 10:46, מאת dmatik ***@***.***>:

**Comment by dmatik** [comment]
לא צריכה להיות בעייה. 
אני מצליח לעשות את כל הדברים האלה גם מאינטגרציה וגם דרך webapi. 
אם האינטגרציה ב-ha יובדת לך, אתה לא צריך את ה-webapi. 
אתה יכול לראות אצלי בגיט את השימוש באינטגרציה לצורך העניין. כולל אוטומציות, צריכה יומית, חודשית, חישוב עלות, הפעלה בתזמונים וכו׳.

**Comment by motti1111** [comment]
נזכרתי, חחח, האינטגרציה לא מוצאת לי את הסוויצר ברשת

מכיר את הבעיה?

בתאריך שבת, 19 באוק׳ 2024, 12:49, מאת dmatik ***@***.***>:
